### ISSUE TITLE
Sensor fails to dispatch because topic is wrong type

### ISSUE THREAD

**Issue by makandre** [StackStorm-Exchange/stackstorm-kafka#12]
I have the sensor configured like so:

```yaml
client_id: StackStorm1
hosts: <some_ip>:9092
message_sensor:
  hosts: <some_ip>:9092
  topics:
  - test
```

But I'm getting the following warning in the sensor when receiving a message, and as a result it doesn't dispatch:

```
2020-07-21 11:06:42,154 WARNING [-] Failed to validate payload ({'topic': b'test', 'partition': 0, 'offset': 59, 'key': None, 'message': {'message': 'test'}}) for trigger "kafka.new_message": b'test' is not of type 'string', 'null'

Failed validating 'type' in schema['properties']['topic']:
    {'description': 'Category from which message was retrieved',
     'type': ['string', 'null']}

On instance['topic']:
    b'test'
```

The topic is expected to be string but looks like it's a byte array. If I changed https://github.com/StackStorm-Exchange/stackstorm-kafka/blob/master/sensors/message_sensor.py#L78 to the following, it would work:

```python
'topic': message.topic.decode('utf8'),
```

**Comment by nmaludy** [comment]
@makandre This indeed looks like a bug with python3 compatibility. Would you be able to submit a PR so that the topic in the trigger payload is properly cast to a string for both python2 & python3?

Thanks for the report!

**Comment by nmaludy** [comment]
Looks like the right way to do this is something like:

```
message.topic.decode('utf-8')
```

Reference: http://net-informations.com/python/iq/byte.htm

**Comment by makandre** [comment]
Hi @nmaludy, I'm new to Python programming.  Please take a look at this PR https://github.com/StackStorm-Exchange/stackstorm-kafka/pull/13

**Comment by makandre** [comment]
Hi @nmaludy, is PR #13 ok?
